version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase.json
    volumes:
      - ./Backend:/app
    networks:
      - app-network

  frontend:
    build: ./Frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

volumes:
  jenkins_data:

networks:
  app-network:

  jenkins_home:
